name: ncue_aiot
description: ncue
publish_to: 'none'
version: 5.3.3+7

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.6
  mqtt_client: ^9.8.1
  webview_flutter: ^2.0.0
  flutter_blue: ^0.8.0
  mysql1: ^0.20.0
  #shelf: ^1.4.1
  #shelf_static: ^1.1.2
  #path_provider: ^2.0.15 #any
  #sqflite: ^2.2.8+4 #any
  #sqljocky5: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
