name: ncue_aiot
description: ncue
publish_to: 'none'
version: 6.3.8+9

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.6
  mqtt_client: ^9.8.1
  provider: ^6.0.0
  webview_flutter: ^2.0.0
  #藍芽部分
  get: ^4.6.5
  flutter_blue_plus: ^1.5.2
  #資料庫
  #mysql1: ^0.20.0
  mysql_client: ^0.0.27

flutter_icons:
  android: "android/app/src/main/res"
  ios: true
  image_path: "assets/images/ic_launcher.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
